linters:
  enable:
    - errcheck
    - errname
    - gocheckcompilerdirectives
    - gocyclo
    - godot
    - lll
    - makezero
    - revive
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    tab-width: 4
    line-length: 79

issues:
  exclude-rules:
    - linters:
        - errcheck
      source: "defer "
  exclude-use-default: false
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
    - (possible misuse of unsafe.Pointer|should have signature)
    - ineffective break statement. Did you mean to break out of the outer loop
    - Use of unsafe calls should be audited
    - Subprocess launch(ed with variable|ing should be audited)
    - G104
    - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
    - Potential file inclusion via variable
